services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - data_volume:/app/data
    expose:
      - 8000
    env_file:
      - .env
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx_http.conf:/etc/nginx/nginx.conf
      #- ./nginx/ssl/selfsigned.crt:/etc/nginx/ssl/selfsigned.crt
      #- ./nginx/ssl/selfsigned.key:/etc/nginx/ssl/selfsigned.key
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  data_volume:
